# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.roastLevelLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.roastLevelLabel.setObjectName("roastLevelLabel")
        self.verticalLayout.addWidget(self.roastLevelLabel)
        self.roastLevelLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.roastLevelLineEdit.setObjectName("roastLevelLineEdit")
        self.verticalLayout.addWidget(self.roastLevelLineEdit)
        self.grindLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.grindLabel.setObjectName("grindLabel")
        self.verticalLayout.addWidget(self.grindLabel)
        self.grindLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.grindLineEdit.setObjectName("grindLineEdit")
        self.verticalLayout.addWidget(self.grindLineEdit)
        self.tasteDescriptionLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.tasteDescriptionLabel.setObjectName("tasteDescriptionLabel")
        self.verticalLayout.addWidget(self.tasteDescriptionLabel)
        self.tasteDescriptionLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.tasteDescriptionLineEdit.setObjectName("tasteDescriptionLineEdit")
        self.verticalLayout.addWidget(self.tasteDescriptionLineEdit)
        self.priceLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.priceLabel.setObjectName("priceLabel")
        self.verticalLayout.addWidget(self.priceLabel)
        self.priceLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.verticalLayout.addWidget(self.priceLineEdit)
        self.packageVolumeLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.packageVolumeLabel.setObjectName("packageVolumeLabel")
        self.verticalLayout.addWidget(self.packageVolumeLabel)
        self.packageVolumeLineEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.packageVolumeLineEdit.setObjectName("packageVolumeLineEdit")
        self.verticalLayout.addWidget(self.packageVolumeLineEdit)
        self.saveButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/редактировать кофе"))
        self.nameLabel.setText(_translate("AddEditCoffeeForm", "Название сорта:"))
        self.roastLevelLabel.setText(_translate("AddEditCoffeeForm", "Степень обжарки:"))
        self.grindLabel.setText(_translate("AddEditCoffeeForm", "Молотый/в зернах:"))
        self.tasteDescriptionLabel.setText(_translate("AddEditCoffeeForm", "Описание вкуса:"))
        self.priceLabel.setText(_translate("AddEditCoffeeForm", "Цена:"))
        self.packageVolumeLabel.setText(_translate("AddEditCoffeeForm", "Объем упаковки:"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
